spring:
  application:
    name: test
server:
  port: 9998
data:
  message: '{cipher}a997989c46cb365373dd11d502801918798f26ad9312808a8f4f352165b4f91f'
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
